### ISSUE TITLE
Works just in terminal, but not in console.

### ISSUE THREAD

**Issue by kamikadza13** [xy3/print-color#10]
![изображение](https://github.com/xy3/print-color/assets/57400507/85736211-e9cb-48d3-82d5-3dc2aba601cf)
![изображение](https://github.com/xy3/print-color/assets/57400507/96cc3a1e-1e5b-47b5-a6dc-5575525bf98b)

**Comment by Odaimoko** [comment]
I think this lib just supports Linux terminal style coloring.
